---
Essential settings:
    fts3 REST endpoint: 'https://fts.coursework.htw:8446/'
    source endpoint: 'https://webdav1.coursework.htw/webdav/'
    destination endpoint: 'https://webdav2.coursework.htw/webdav'

SSL settings:
    path of user certificate: '/coursework/certs/client.crt'
    path of user key: '/coursework/certs/client.key'
    verify host: False

Synchronization settings:
    action for modified file: 'ignore'
    sync interval in minutes: 1
    dry run: False
    single run: False
    exclude:
      - '*.DS_Store'

DAV settings:
    verbose: False

Logging:
    log level: 'DEBUG'
    # path of logging file: '/fts.log'
...

